import SITE_URL from "../config";

export const checkIfMetamaskConnected = async () => {
  if (window.ethereum) {
    try {
      const accounts = await window.ethereum.request({
        method: "eth_requestAccounts",
      });
      if (accounts.length > 0) {
        checkIfPolygonInMetamask();
      }
    } catch (error) {
      console.log(error);
    }
  }
};

export const checkIfPolygonInMetamask = async () => {
  if (window.ethereum) {
    try {
      const chainId = await window.ethereum.request({
        method: "eth_chainId",
      });
      if (chainId !== "0x13882") {
        switchPolygonInMetamask();
      }
    } catch (error) {
      console.log(error);
    }
  }
};

export const switchPolygonInMetamask = async () => {
  if (window.ethereum) {
    try {
      await window.ethereum.request({
        method: "wallet_switchEthereumChain",
        params: [{ chainId: "0x13882" }],
      });
    } catch (error) {
      console.log(error);
      addPolygonToMetamask();
    }
  }
};

export const addPolygonToMetamask = async () => {
  if (window.ethereum) {
    try {
      await window.ethereum.request({
        method: "eth_chainId",
      });
    } catch (error) {
      console.log(error);
      return;
    }
    try {
      await window.ethereum.request({
        method: "wallet_addEthereumChain",
        params: [
          {
            chainId: "0x13882",
            chainName: "Matic Amoy",
            nativeCurrency: {
              name: "MATIC",
              symbol: "MATIC",
              decimals: 18,
            },
            rpcUrls: ["https://polygon-amoy.drpc.org/"],
            blockExplorerUrls: ["https://amoy.polygonscan.com/"],
          },
        ],
      });
    } catch (error) {
      console.log(error);
    }
  }
};

export function ImageUrl(url) {
  return SITE_URL + url;
}

export const bikeBrands = [
  "A-Pro",
  "Abici",
  "Adrenaline",
  "Aether",
  "Airstreeem",
  "Alan",
  "Alchemy",
  "Alé",
  "Alexander Leiter",
  "Alpina",
  "Alta",
  "Ammaco",
  "Ampler",
  "Ancheer",
  "Apex",
  "Apollo",
  "Argon 18",
  "Ariel Rider",
  "Atala",
  "Author",
  "Avigo",
  "BH Bikes",
  "Bianchi",
  "Bike Friday",
  "Bike Ribbon",
  "Bike-Mailorder",
  "BikeAid",
  "BikeFrameBuilder",
  "BikeTouring",
  "BikeTouringNews",
  "BikeTouringTips",
  "BikeTube",
  "Biknd",
  "Bill Holland",
  "Binns Road",
  "BMC",
  "BMC Switzerland",
  "Bobbin",
  "Bohemian Bicycles",
  "Bolt",
  "Bombtrack",
  "Bottecchia",
  "Bradley Wiggins",
  "Breezer",
  "Bridgestone",
  "Brodie",
  "Brooks England",
  "Brown Cycles",
  "Bruce Gordon",
  "BSP",
  "Budnitz",
  "Bulls",
  "Bura Bikes",
  "Butchers & Bicycles",
  "Calfee",
  "Calibre",
  "Caloi",
  "Canyon",
  "Cannondale",
  "Carbon Cycles",
  "Carey Price",
  "Carrera",
  "Cervelo",
  "Charge Bikes",
  "Chater-Lea",
  "Cinelli",
  "Claud Butler",
  "Claudy Jongstra",
  "Coker",
  "Colnago",
  "Columbus",
  "Condor",
  "Co-op Cycles",
  "Corima",
  "Corratec",
  "Cube",
  "Curtis Bikes",
  "Cycle-Works",
  "CycleOps",
  "CycleSurgery",
  "Cycloc",
  "Cyclon",
  "Dahon",
  "Dawes",
  "De Rosa",
  "Decathlon",
  "Deuter",
  "Diamondback",
  "Diamant",
  "Diamant Bikes",
  "Diff",
  "DirtySixer",
  "Dolan Bikes",
  "Donkey Label",
  "Dorel",
  "Downtube",
  "Drahtesel",
  "Dressler",
  "Drunbi",
  "DynaTech",
  "Eddy Merckx",
  "Elite",
  "Ellis Briggs",
  "Empella",
  "Engin",
  "Enigma",
  "Evans Cycles",
  "Felt",
  "Foffa Bikes",
  "Focus",
  "Fort Cycles",
  "Framed Bikes",
  "Free Agent",
  "Free Spirit",
  "Fuji",
  "Gazelle",
  "Giant",
  "Gitane",
  "Globe",
  "Gocycle",
  "Good Bike",
  "Gore Bike Wear",
  "Gravity",
  "GT",
  "Guerciotti",
  "Haro",
  "Hase Bikes",
  "Haibike",
  "Hercules",
  "Hero",
  "Hillbrick Bicycles",
  "Hoffman Bikes",
  "Holiday",
  "Huffy",
  "Ibis",
  "Iron Horse",
  "Izumi",
  "Jan Janssen",
  "Jamis",
  "Java",
  "Jett",
  "Kalkhoff",
  "Kawasaki",
  "Kellys",
  "Kestrel",
  "KHS",
  "Kink",
  "Kona",
  "Kross",
  "KTM",
  "Kuota",
  "La Pierre",
  "Lapierre",
  "LeMond",
  "Litespeed",
  "Look",
  "Lotus",
  "Lynskey",
  "Masi",
  "Matra",
  "Mekk",
  "Merida",
  "Miele",
  "Miyata",
  "Monark",
  "Mongoose",
  "Montague",
  "Moots",
  "Moss",
  "Mouvement",
  "MTB Cycletech",
  "Mudhugger",
  "Murray",
  "Nashbar",
  "Niner",
  "Nishiki",
  "Norco",
  "Northrock",
  "Novara",
  "NS Bikes",
  "Nukeproof",
  "OES",
  "Olympia",
  "Omnium",
  "OPP",
  "Orange",
  "Orbea",
  "Origin8",
  "Orro",
  "Pashley",
  "Peugeot",
  "Phat Cycles",
  "Pinarello",
  "Pocket",
  "Polygon",
  "Pony Bikes",
  "Prairie Sprout",
  "Princeton",
  "ProdecoTech",
  "Puch",
  "Pure Cycles",
  "Quantum",
  "Quintana Roo",
  "Rad Power Bikes",
  "Radon",
  "Raleigh",
  "Redline",
  "Regina",
  "Reid",
  "Ridley",
  "Ritchey",
  "Rock Machine",
  "Rocky Mountain",
  "Rohloff",
  "Rolly",
  "Rose",
  "Roubaix",
  "Rudge",
  "Schwinn",
  "Scott",
  "SE Bikes",
  "Shogun",
  "Simpson",
  "Sinclair",
  "Simplon",
  "Sixthreezero",
  "SJSC",
  "Specialized",
  "Squishy Bikes",
  "Staiger",
  "State Bicycle Co.",
  "Stevens",
  "Steve Potts",
  "Storck",
  "Stradalli",
  "Strider",
  "Surly",
  "Swobo",
  "Tern",
  "Thompson",
  "Thule",
  "ThyssenKrupp",
  "Tomac",
  "Tomassini",
  "Tommaso",
  "Topstone",
  "Transition",
  "Trek",
  "Triban",
  "Triumph",
  "Tucano",
  "Univega",
  "Upland",
  "Urkai",
  "Vanmoof",
  "Vitus",
  "Viva",
  "Voodoo",
  "Votec",
  "Wahoyo",
  "Waterford",
  "Watt",
  "Wayel",
  "WeThePeople",
  "Whistle",
  "Whyte",
  "Wilier",
  "Winora",
  "Witcomb",
  "Wizard",
  "Woolf Tooth Components",
  "Wright Cycle Company",
  "XLC",
  "Yeti",
  "Yondering",
  "Yuba",
  "Zebrakenko",
  "Zinn",
  "Zullo",
  "Zunow",
];
